name: ReadMeGenAI

services:
  consul-service:
    image: consul:1.15.0
    container_name: consul-service
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    networks:
      - discovery-service-network

  prompt-service:
    build:
      context: '../PromptService'
      dockerfile: Dockerfile
    container_name: prompt-service
    environment:
      - PORT=9010
      - NAME=prompt-service
    ports:
      - "9010:9010"
    depends_on:
      - consul-service
    networks:
      - discovery-service-network

  readme-writer:
    build:
      context: '../LLM'
      dockerfile: Dockerfile
    container_name: readme-writer
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    networks:
      - ai-network

  readme-service:
    build:
      context: '../ReadmeService'
      dockerfile: Dockerfile
    container_name: readme-service
    ports:
      - "9020:9020"
    depends_on:
      - consul-service
      - readme-writer
    networks:
      - discovery-service-network
      - ai-network

volumes:
  ollama-models:

networks:
  discovery-service-network:
  ai-network: