name: CI Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  prompt-service-tests:
    name: Run Prompt Service Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js v22.14.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./PromptService

      - name: Run Node.js tests
        run: npm test
        working-directory: ./PromptService

  readme-service-tests:
    name: Run Readme Service Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run Spring Boot tests
        run: mvn clean verify
        working-directory: ./ReadmeService

  readme-frontend-tests:
    name: Run React Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js v22.14.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./readme-gen-frontend

      - name: Run React tests
        run: npm test
        working-directory: ./readme-gen-frontend
